### ISSUE TITLE
Blank page is displayed

### ISSUE THREAD

**Issue by psafa** [adrian-hintze/Snapp#23] opened 2018-07-30 20:04 UTC
Nothing is displayed in the generated executable.
Snap! v4.2.1.3
MacOS 10.11.6

![image](https://user-images.githubusercontent.com/5198544/43420585-08971cb8-93f9-11e8-86e1-d537770ac959.png)

![image](https://user-images.githubusercontent.com/5198544/43420507-c42fcd90-93f8-11e8-88cc-b330355f4f7c.png)

**Comment by ZeRipper** [comment] 2018-08-05 17:01
Same issue here. Tested with a simple project then with the "copter" sample project. Only a blank window opening. On Mac, 64 bits.

**Comment by psafa** [comment] 2018-08-17 17:41
Hi Adrian,
I was away and couldn't write back sooner. I have attached the .xml. It
happens with anything I have tried so far. Thanks for looking into it.



*Parisa Safa*

*Mathematics Department Chair*

*Urban School of San Francisco*

*psafa@urbanschool.org <psafa@urbanschool.org>(415) 593-9568 *

**Comment by Rydion** [comment] 2018-08-18 00:31
Hi @psafa I finally got hold of a mac and found out what the issue is. It's not related to the project. Expect a fix soon.

**Comment by Rydion** [comment] 2018-08-28 20:04
Hi, just as a heads up to everyone. As mentioned I know what the issue is. My biggest hurdle right now is that I have lost access to the hosting I was using, it may take a good week before I get it back. I will be implementing the fix in the meantime.

**Comment by psafa** [comment] 2018-08-28 20:11
Thank you!



*Parisa Safa*

*Mathematics Department Chair*

*Urban School of San Francisco*

*psafa@urbanschool.org <psafa@urbanschool.org>(415) 593-9568 *

**Comment by Rydion** [comment] 2018-09-18 19:11
@psafa @ZeRipper I have updated Snapp, can you test your projects and confirm if everything is working correctly for you?

**Comment by adrian-hintze** [comment] 2018-10-17 17:54
Closing as this should be fixed and I'm getting no feedback.

**Closed by adrian-hintze** 2018-10-17 17:54 UTC
Labels: bug

**Comment by psafa** [comment] 2018-10-17 18:39
Yes, sorry. I thought I had replied. It's totally fixed.  Thank you.



*Parisa Safa*

*Mathematics Department Chair*

*Urban School of San Francisco*

*psafa@urbanschool.org <psafa@urbanschool.org>(415) 593-9568 *

**Comment by adrian-hintze** [comment] 2018-10-17 19:11
@psafa Thank you for letting me know. Glad this is working now.
